
server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: {db-password}
    username: {db-password}
  mail:
    host: smtp.gmail.com
    port: 587
    username: {email}
    password: {senha}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
